# Generated by Django 2.1.7 on 2019-02-17 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, verbose_name='姓名')),
                ('contact_way', models.CharField(choices=[('qq', 'QQ号'), ('tel', '手机号码')], default=('qq', 'QQ号'), max_length=5, verbose_name='联系方式')),
                ('contact_info', models.CharField(max_length=20, verbose_name='联系信息')),
                ('is_finish', models.BooleanField(default=False, verbose_name='是否完成')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
            ],
            options={
                'verbose_name': '服务订单',
                'verbose_name_plural': '服务订单',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='服务名称')),
                ('price', models.CharField(max_length=10, verbose_name='价格(元)')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
            ],
            options={
                'verbose_name': '服务类型',
                'verbose_name_plural': '服务类型',
                'ordering': ('title',),
            },
        ),
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='services.Service', verbose_name='服务类型'),
        ),
    ]
