# Generated by Django 2.1.7 on 2019-02-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contact_way',
            field=models.CharField(choices=[('qq', 'QQ号'), ('tel', '手机号码')], default=('qq', 'QQ号'), max_length=8, verbose_name='联系方式'),
        ),
    ]
