# Generated by Django 2.1.7 on 2019-03-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='img_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='图片链接'),
        ),
    ]
