# Generated by Django 2.1.7 on 2019-03-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
