# Generated by Django 2.1.7 on 2019-03-17 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_service_view_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='description',
            new_name='overview',
        ),
    ]
