# Generated by Django 2.1.7 on 2019-03-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='purpose',
            field=models.CharField(max_length=200, null=True, verbose_name='宗旨'),
        ),
        migrations.AddField(
            model_name='about',
            name='service',
            field=models.TextField(null=True, verbose_name='特色服务'),
        ),
        migrations.AddField(
            model_name='about',
            name='team_name',
            field=models.CharField(max_length=64, null=True, verbose_name='团队名称'),
        ),
        migrations.AlterField(
            model_name='about',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
