# Generated by Django 2.1.7 on 2019-03-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abouts', '0003_auto_20190317_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True, verbose_name='是否接收')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '接收订单邮箱管理',
                'verbose_name_plural': '接收订单邮箱管理',
                'ordering': ('-created',),
            },
        ),
    ]
